name: build

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - '*.md'
      - '**/*.yml'
    branches:
      - main

jobs:
  build:
    name: Build Re-compose Library
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant permission for Gradle to execute
        run: chmod +x gradlew

      - uses: gradle/gradle-build-action@v2

      - name: Spotless check
        run: ./gradlew spotlessCheck

      - name: Run tests
        run: ./gradlew :recompose:check --stacktrace

      - name: Publish snapshots 🚀
        run: ./gradlew :recompose:publishAllPublicationsToDeployRepository

      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: error-report
          path: build-reports.zip

env:
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
